bulk=read.csv("BULK.csv")
human=subset(bulk, bulk$species =="human")
animal=subset(bulk, bulk$species =="herbivore" | bulk$species =="camelid"| bulk$species =="caprine"|  bulk$species =="ovicaprid"|  bulk$species == "goat"|  bulk$species == "sheep"|   bulk$species == "wild sheep"| bulk$species == "ibex"|  bulk$species =="bos"|  bulk$species =="cattle"| bulk$species =="boar"| bulk$species =="pig"| bulk$species =="carp"| bulk$species =="fish"| bulk$species == "pike"| bulk$species == "sazan"| bulk$species =="deer"|  bulk$species =="red deer"|  bulk$species =="roe deer"| bulk$species == "wild deer"|  bulk$species =="donkey"| bulk$species == "hemione"|  bulk$species =="horse"| bulk$species == "gazella"|  bulk$species =="saiga"|  bulk$species =="bear"|  bulk$species =="cat"|  bulk$species =="dog"| bulk$species == "wolf"| bulk$species == "tortoise")
plot(bulk$carbon, bulk$nitrogen, main="Carbon and Nitrogen Isotopic Ratios", xlab="δ13C‰", ylab="δ15N‰", col="lightblue", pch=20)
ggplot(bulk, mapping=aes(x=carbon, y=nitrogen)) + geom_point() + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios") 
ggplot(bulk, mapping=aes(x=carbon, y=nitrogen, col=species)) + geom_point() + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios")
install.packages("ggplot2")
library(ggplot2)
install.packages("RColorBrewer") 
library(RColorBrewer) 
install.packages("ggpubr")
library("ggpubr")
ggplot(bulk, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point() + bgcolor("#BFD5E3") + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios") 
ggplot(bulk, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point() + bgcolor("linen") + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-30, -5), ylim=c(0,20), expand=FALSE)
socioeconomic=subset(bulk, bulk$SOCIOECONOMIC == "NOMADIC"|bulk$SOCIOECONOMIC == "URBAN")
ggplot(socioeconomic, mapping=aes(x=carbon, y=nitrogen, col=SOCIOECONOMIC)) + geom_point(size=1) + bgcolor("linen") + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios for Nomadic and Urban Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(2.5,20), expand=FALSE)
ggplot(environment, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=0.65) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios for Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,20), expand=FALSE)
ggplot(chronology, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=0.75) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios for Different Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(0,20), expand=FALSE)
chronology=subset(bulk, !bulk$CHRONOLOGY%in%c("MODERN", "pre-BRONZE AGE"))
animals=subset(bulk, !bulk$species%in%c("human",""))
ggplot(animals, mapping=aes(x=carbon, y=nitrogen, col=species)) + geom_point(size=0.75) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios for Different Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,17.5), expand=FALSE)
ggplot(human, mapping=aes(x=carbon, y=nitrogen, col="orange")) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(5,20), expand=FALSE)
ggplot(human, mapping=aes(x=carbon, y=nitrogen, col="orange")) + geom_point(size=1, show.legend=FALSE) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(5,20), expand=FALSE)
ggplot(human, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(5,20), expand=FALSE)
environment=subset(bulk, bulk$ENVIRONMENT == "A - SEMI-ARID STEPPE"|bulk$ENVIRONMENT == "B - FOREST STEPPE"| bulk$ENVIRONMENT == "C - WEST STEPPE"| bulk$ENVIRONMENT == "D - MOUNTAIN/FOREST STEPPE"| bulk$ENVIRONMENT == "E - ARID/MOUNTAIN STEPPE"| bulk$ENVIRONMENT == "F - DESERT OASES"| bulk$ENVIRONMENT == "G - ARID DESERT")
ggplot(animalenvironment, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=0.9) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,17.5), expand=FALSE)
animalenvironment=subset(environment, !environment$species%in%c("human",""))
humanchronology=subset(chronology, chronology$species =="human")
ggplot(humanchronology, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Different Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(5,20), expand=FALSE)
animalchronology=subset(chronology, !chronology$species%in%c("human",""))
ggplot(animalchronology, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Different Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(0,17.5), expand=FALSE)
ggplot(humansocioeconomic2, mapping=aes(x=carbon, y=nitrogen, col=SOCIOECONOMIC)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Urban or Nomadic settings")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(7.5,20), expand=FALSE)
humansocioeconomic2=subset(socioeconomic2, socioeconomic2$species=="human")
animalsocioeconomic2=subset(socioeconomic2, !socioeconomic2$species%in%c("human",""))
ggplot(animalsocioeconomic2, mapping=aes(x=carbon, y=nitrogen, col=SOCIOECONOMIC)) + geom_point(size=0.9) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Urban or Nomadic settings")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,17.5), expand=FALSE)
ggplot(humanbronzeage, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Bronze Age Humans in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-12.5), ylim=c(7.5,19), expand=FALSE) +font("title", size=11)
animalbronzeage=subset(bronzeage, !bronzeage$species%in%c("human",""))
animalenvbage=subset(animalenvironment, animalenvironment$CHRONOLOGY=="BRONZE AGE")
ggplot(animalenvbage, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Bronze Age Animals in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(0,15), expand=FALSE) +font("title", size=11)
ggplot(humanironage, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Iron Age Humans in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(7.5,20), expand=FALSE) +font("title", size=11)
ironage=subset(bulk, bulk$CHRONOLOGY=="IRON AGE")
humanironage=subset(ironage, ironage$species=="human")
lateant=subset(bulk, bulk$CHRONOLOGY=="LATE ANTIQUITY")
humanlateant=subset(lateant, lateant$species=="human")
medieval=subset(bulk, bulk$CHRONOLOGY=="MEDIEVAL")
humanmedieval=subset(medieval, medieval$species=="human")
ggplot(humanlateant, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Late Antiquity Humans in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-30,-5), ylim=c(0,20), expand=FALSE) +font("title", size=11)
ggplot(humanlateant, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Late Antiquity Humans in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(10,17.5), expand=FALSE) +font("title", size=11)
ggplot(humanmedieval, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Medieval Humans in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-20,-10), ylim=c(7.5,17.5), expand=FALSE) +font("title", size=11)
ggplot(anenvironage, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=1.6) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Iron Age Animals in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(0,15), expand=FALSE) +font("title", size=11)
anenvironage=subset(animalenvironment,animalenvironment$CHRONOLOGY=="IRON AGE")
ggplot(anenvlateant, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Late Antiquity Animals in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-12.5), ylim=c(2.5,15), expand=FALSE) +font("title", size=11)
anenvlateant=subset(animalenvironment, animalenvironment$CHRONOLOGY=="LATE ANTIQUITY")
anenvmedieval=subset(animalenvironment, animalenvironment$CHRONOLOGY=="MEDIEVAL")
ggplot(anenvmedieval, mapping=aes(x=carbon, y=nitrogen, col=ENVIRONMENT)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Medieval Animals in Different Environments")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(5,17.5), expand=FALSE) +font("title", size=11)
ggplot(humanA, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Semi-Arid Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(7.5,20), expand=FALSE) +font("title", size=11)
humanA=subset(human, human$ENVIRONMENT=="A - SEMI-ARID STEPPE")
ggplot(humanB, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Forest Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-15), ylim=c(7.5,17.5), expand=FALSE) +font("title", size=11)
humanB=subset(human, human$ENVIRONMENT=="B - FOREST STEPPE")
humanC=subset(human, human$ENVIRONMENT=="C - WEST STEPPE")
ggplot(humanC, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in West Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-20,-12.5), ylim=c(10,20), expand=FALSE) +font("title", size=11)
humanD=subset(human, human$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
ggplot(humanD, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Mountain/Forest Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(7.5,15), expand=FALSE) +font("title", size=11)
humanE=subset(human, human$ENVIRONMENT=="E - ARID MOUNTAIN STEPPE")
humanF=subset(human, human$ENVIRONMENT=="F - DESERT OASES")
ggplot(humanF, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Desert Oases Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(7.5,17.5), expand=FALSE) +font("title", size=11)
humanG=subset(human, human$ENVIRONMENT=="G - ARID DESERT")
ggplot(humanG, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=3) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Arid Desert Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-15), ylim=c(10,17.5), expand=FALSE) +font("title", size=11)
animalsA=subset(animals, animals$ENVIRONMENT=="A - SEMI-ARID STEPPE")
ggplot(animalsA, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Semi-Arid Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.55,-10), ylim=c(2.5,20), expand=FALSE) +font("title", size=11)
animalsB=subset(animals, animals$ENVIRONMENT=="B - FOREST STEPPE")
ggplot(animalsB, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Forest Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-15), ylim=c(2.5,17.5), expand=FALSE) +font("title", size=11)
animalsC=subset(animals, animals$ENVIRONMENT=="C - WEST STEPPE")
ggplot(animalsC, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1.5) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in West Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(2.5,20), expand=FALSE) +font("title", size=11)
animalsD=subset(animals, animals$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
ggplot(animalsD, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1.5) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Mountain/Forest Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,17.5), expand=FALSE) +font("title", size=11)
animalsE=subset(animals, animals$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
ggplot(animalsE, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Arid/Mountain Steppes Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,17.5), expand=FALSE) +font("title", size=11)
animalsF=subset(animals, animals$ENVIRONMENT=="F - DESERT OASES")
ggplot(animalsF, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1.5) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Desert Oases Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(2.5,17.5), expand=FALSE) +font("title", size=11)
animalsG=subset(animals, animals$ENVIRONMENT=="G - ARID DESERT")
ggplot(animalsG, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=3) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Animals in Arid Desert Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(5,17.5), expand=TRUE) +font("title", size=11)
urban=subset(bulk, bulk$SOCIOECONOMIC=="URBAN")
urbanhuman=subset(urban, urban$species=="human")
ggplot(urbanhuman, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Urban Societies Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(7.5,15), expand=FALSE) +font("title", size=11)
nomadic=subset(bulk, bulk$SOCIOECONOMIC=="NOMADIC")
nomadichuman=subset(nomadic, nomadic$species=="human")
ggplot(nomadichuman, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1.5) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans in Nomadic Societies Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-20,-10), ylim=c(7.5,20), expand=FALSE) +font("title", size=11)
ggplot(begash, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Begash Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(0,15), expand=FALSE) +font("title", size=11)
begash=subset(bulk, bulk$site=="Begash")
turgen=subset(bulk, bulk$site=="Turgen"| bulk$site=="Turgen 2"| bulk$site=="Turgen-2")
humanturgen=subset(turgen, turgen$species=="human")
ggplot(humanturgen, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Turgen Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-20,-12.5), ylim=c(10,14), expand=FALSE) +font("title", size=11)
Kainarbulak=subset(bulk, bulk$site=="Kainar Bulak"| bulk$site=="Kainar Bulak-1"| bulk$site=="Kainarbulak-1"| bulk$site=="Kainarbulak-2")
ggplot(Kainarbulak, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Kainarbulak Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(0,15), expand=FALSE) +font("title", size=12)
ggplot(GeoktchikDepe, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Geoktchik Depe Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-30,-5), ylim=c(0,20), expand=FALSE) +font("title", size=11)
GeoktchikDepe=subset(bulk, bulk$site=="Geoktchik Depe")
ggplot(humanBestamak, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans at Bestamak Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-15), ylim=c(7.5,15), expand=FALSE) +font("title", size=13)
Bestamak=subset(bulk, bulk$site=="Bestamak")
humanBestamak=subset(Bestamak, Bestamak$species=="human")
Aktogai=subset(bulk, bulk$site=="Aktogai")
ggplot(Aktogai, mapping=aes(x=carbon, y=nitrogen, col=CHRONOLOGY)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Humans at Aktogai Across Periods")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-20,-15), ylim=c(10,17.5), expand=FALSE) +font("title", size=13)
A=subset(bulk, bulk$ENVIRONMENT=="A - SEMI-ARID STEPPE")
ggplot(A, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1, show.legend=FALSE) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Semi-Arid Steppe Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-10), ylim=c(2.5,20), expand=FALSE) +font("title", size=11)
ggplot(A, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Semi-Arid Steppe Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-30,-5), ylim=c(0,20), expand=FALSE) +font("title", size=11)

B=subset(bulk, bulk$ENVIRONMENT=="B - FOREST STEPPE")
ggplot(B, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Forest Steppe Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-15), ylim=c(2.5,17.5), expand=FALSE) +font("title", size=11)
C=subset(bulk, bulk$ENVIRONMENT=="C - WEST STEPPE")
ggplot(C, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=2) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of West Steppe Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-22.5,-12.5), ylim=c(2.5,20), expand=FALSE) +font("title", size=13)
D=subset(bulk, bulk$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
ggplot(D, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Mountain/Forest Steppe Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-30,-12.5), ylim=c(0,15)) +font("title", size=11)
E=subset(bulk, bulk$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
ggplot(E, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Arid/Mountain Steppe Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-27.5,-10), ylim=c(0,17.5), expand=FALSE) +font("title", size=11)
F=subset(bulk, bulk$ENVIRONMENT=="F - DESERT OASES")
ggplot(F, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Desert Oases Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(2.5,17.5), expand=FALSE) +font("title", size=12)
G=subset(bulk, bulk$ENVIRONMENT=="G - ARID DESERT")
ggplot(G, mapping=aes(x=carbon, y=nitrogen, col=site)) + geom_point(size=1) + labs(x="δ13C‰", y="δ15N‰", title="Carbon and Nitrogen Isotopic Ratios of Arid Desert Sites")+ theme_bw() + scale_y_continuous(position = "left") + coord_cartesian(xlim = c(-25,-10), ylim=c(5,20), expand=FALSE) +font("title", size=13)
nomadanimals2=subset(animals, animals$SOCIOECONOMIC=="NOMADIC")
hist(nomadanimals2$carbon, xlab="δ13C‰", main="Carbon data for animals in Nomadic Settings", col="lavender")
urbananimals=subset(animals, animals$SOCIOECONOMIC=="URBAN")
hist(urbananimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Urban Settings", col="lightblue")
shapiro.test(urbananimals$carbon)
wilcox.test(x=nomadanimals2$carbon, y=urbananimals$carbon)
hist(nomadanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Nomadic Settings", col="turquoise4")
hist(urbananimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Urban Settings", col="orange")
shapiro.test(urbananimals$nitrogen)
wilcox.test(x=nomadanimals2$nitrogen, y=urbananimals$nitrogen)
hist(nomadanimals2$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Nomadic Settings", col="lightpink")
shapiro.test(nomadanimals2$oxygen)
hist(urbananimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Urban Settings", col="yellowgreen")
shapiro.test(urbananimals$oxygen)
wilcox.test(x=nomadanimals2$oxygen, y=urbananimals$oxygen)
nomadhuman=subset(human, human$SOCIOECONOMIC=="NOMADIC")
hist(nomadhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Nomadic Settings", col="tomato3")
shapiro.test(nomadhuman$carbon)
urbanhuman=subset(human, human$SOCIOECONOMIC=="URBAN")
hist(urbanhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Urban Settings", col="steelblue")
shapiro.test(urbanhuman$carbon)
wilcox.test(x=urbanhuman$carbon, y=nomadhuman$carbon)
hist(nomadhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Nomadic Settings", col="salmon")
shapiro.test(nomadhuman$nitrogen)
hist(urbanhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Urban Settings", col="navajowhite")
shapiro.test(urbanhuman$nitrogen)
t.test(x=urbanhuman$nitrogen, y=nomadhuman$nitrogen)
hist(nomadhuman2$oxygen, xlab="δ18O‰", main="Oxygen data for humans in nomadic Settings", col="salmon")
shapiro.test(nomadhuman2$oxygen)
mean(nomadhuman2$oxygen, na.rm=TRUE)
t.test(x=nomadhuman2$oxygen, -6.7, var.equal=TRUE)
Aanimals=subset(animals, animals$ENVIRONMENT=="A - SEMI-ARID STEPPE")
hist(Aanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Semi Arid Steppe", col="olivedrab4")
shapiro.test(Aanimals$carbon)
Banimals=subset(animals, animals$ENVIRONMENT=="B - FOREST STEPPE")
hist(Banimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Forest Steppe", col="saddlebrown")
shapiro.test(Banimals$carbon)
Canimals=subset(animals, animals$ENVIRONMENT=="C - WEST STEPPE")
hist(Canimals$carbon, xlab="δ13C‰", main="Carbon data for animals in West Steppe", col="palevioletred1")
shapiro.test(Canimals$carbon)
Danimals=subset(animals, animals$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
hist(Danimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Mountain/Forest Steppe", col="peachpuff4")
shapiro.test(Danimals$carbon)
Eanimals=subset(animals, animals$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
hist(Eanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Arid/Mountain Steppe", col="magenta4")
shapiro.test(Eanimals$carbon)
Fanimals=subset(animals, animals$ENVIRONMENT=="F - DESERT OASES")
hist(Fanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Desert Oases", col="dodgerblue")
shapiro.test(Fanimals$carbon)
Ganimals=subset(animals, animals$ENVIRONMENT=="G - ARID DESERT")
hist(Ganimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Arid Desert", col="indianred3")
kruskal.test(animals$carbon ~ animals$ENVIRONMENT, data=animals) 
install.packages("rstatix")
dunn_test(animals, carbon ~ ENVIRONMENT)
CanimalsEnvironment =dunn_test(animals, carbon ~ ENVIRONMENT)
summary(CanimalsEnvironment)
hist(Aanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Semi - Arid Steppe", col="firebrick4")
shapiro.test(Aanimals$nitrogen)
hist(Banimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Forest Steppe", col="forestgreen")
shapiro.test(Banimals$nitrogen)
hist(Canimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in West Steppe", col="rosybrown1")
shapiro.test(Canimals$nitrogen)
hist(Danimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Mountain/Forest Steppe", col="wheat4")
shapiro.test(Danimals$nitrogen)
hist(Eanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid/Mountain Steppe", col="tan2")
shapiro.test(Eanimals$nitrogen)
hist(Fanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Desert Oases", col="mediumpurple")
shapiro.test(Fanimals$nitrogen)
hist(Ganimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid Desert", col="lemonchiffon2")
shapiro.test(Ganimals$nitrogen)
kruskal.test(animals$nitrogen ~ animals$ENVIRONMENT, data=animals)
Nanimalsenvironment = dunn_test(animals, nitrogen ~ ENVIRONMENT)
summary(Nanimalsenvironment)
hist(Aanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Semi-Arid Steppe", col="slateblue2")
shapiro.test(Aanimals$oxygen)
hist(Danimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Mountain/Forest Steppe", col="skyblue")
shapiro.test(Danimals$oxygen)
hist(Eanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid/Mountain Steppe", col="mediumaquamarine")
shapiro.test(Eanimals$oxygen)
hist(Ganimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid Desert", col="seagreen")
shapiro.test(Ganimals$oxygen)
oneway.test(animals$oxygen ~ animals$ENVIRONMENT, data=animals)
result=aov(animals$oxygen ~ animals$ENVIRONMENT, data=animals)
TukeyHSD(result)
DTN=dunn_test(animals, nitrogen ~ ENVIRONMENT)
View(DTN)
DTC=dunn_test(animals, carbon ~ ENVIRONMENT)
View(DTC)
plot(result)
T=TukeyHSD(result)
plot(T, las=1)
par(mar=c(5,27,4,1))
plot(T, las=1)
Ahuman=subset(human, human$ENVIRONMENT=="A - SEMI-ARID STEPPE")
par(mar=c(4,4,4,4))
hist(Ahuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Semi-Arid Steppe", col="springgreen4")
shapiro.test(Ahuman$carbon)
Bhuman=subset(human, human$ENVIRONMENT=="B - FOREST STEPPE")
hist(Bhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Forest Steppe", col="slategrey")
shapiro.test(Bhuman$carbon)
Chuman=subset(human, human$ENVIRONMENT=="C - WEST STEPPE")
hist(Chuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in West Steppe", col="sienna3")
shapiro.test(Chuman$carbon)
Dhuman=subset(human, human$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
hist(Dhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Mountain/Forest Steppe", col="plum3")
shapiro.test(Dhuman$carbon)
Ehuman=subset(human, human$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
hist(Ehuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Arid/Mountain Steppe", col="hotpink2")
shapiro.test(Ehuman$carbon)
Fhuman=subset(human, human$ENVIRONMENT=="F - DESERT OASES")
hist(Fhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Desert Oases", col="paleturquoise2")
shapiro.test(Fhuman$carbon)
Ghuman=subset(human, human$ENVIRONMENT=="G - ARID DESERT")
hist(Ghuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Arid Desert", col="lavenderblush3")
shapiro.test(Ghuman$carbon)
kruskal.test(human$carbon~human$ENVIRONMENT, data=human)
DTCH=dunn_test(human, carbon ~ ENVIRONMENT)
summary(DTCH)
View(DTCH)
hist(Ahuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Semi-Arid Steppe", col="violet")
shapiro.test(Ahuman$nitrogen)
hist(Bhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Forest Steppe", col="orangered3")
shapiro.test(Bhuman$nitrogen)
hist(Chuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in WEST Steppe", col="lightsteelblue2")
shapiro.test(Chuman$nitrogen)
hist(Dhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Mountain/Forest Steppe", col="olivedrab")
shapiro.test(Dhuman$nitrogen)
hist(Ehuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Arid/Mountain Steppe", col="mediumorchid")
shapiro.test(Ehuman$nitrogen)
hist(Fhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in DESERT OASES", col="royalblue4")
shapiro.test(Fhuman$nitrogen)
hist(Ghuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Arid Desert", col="khaki1")
shapiro.test(Ghuman$nitrogen)
kruskal.test(human$nitrogen~human$ENVIRONMENT, data=human)
DTNH=dunn_test(human, nitrogen ~ ENVIRONMENT)
summary(DTNH)
View(DTNH)
hist(Bhuman$oxygen, xlab="δ18O‰", main="Oxygen data for Humans in Forest Steppe", col="thistle2")
shapiro.test(Bhuman$oxygen)
Bronzeanimals=subset(animals, animals$CHRONOLOGY=="BRONZE AGE")
hist(Bronzeanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Bronze Age", col="powderblue")
shapiro.test(Bronzeanimals$carbon)
Ironanimals=subset(animals, animals$CHRONOLOGY=="IRON AGE")
hist(Ironanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Iron Age", col="ivory3")
shapiro.test(Ironanimals$carbon)
LANTanimals=subset(animals, animals$CHRONOLOGY=="LATE ANTIQUITY")
hist(LANTanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Late Antiquity", col="pink2")
shapiro.test(LANTanimals$carbon)
Medievalanimals=subset(animals, animals$CHRONOLOGY=="MEDIEVAL")
hist(Medievalanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Medieval", col="lemonchiffon1")
shapiro.test(Medievalanimals$carbon)
kruskal.test(animals$carbon~animals$CHRONOLOGY, data=animals)
DTCCA=dunn_test(animals, carbon ~ CHRONOLOGY)
summary(DTCCA)
hist(Bronzeanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in the Bronze Age", col="sandybrown")
shapiro.test(Bronzeanimals$nitrogen)
hist(Ironanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in the Iron Age", col="burlywood3")
shapiro.test(Ironanimals$nitrogen)
hist(LANTanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in Late Antiquity", col="mistyrose3")
shapiro.test(LANTanimals$nitrogen)
hist(Medievalanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in the Medieval Period", col="lawngreen")
shapiro.test(Medievalanimals$nitrogen)
kruskal.test(animals$nitrogen~animals$CHRONOLOGY, data=animals)
DTCNA=dunn_test(animals, nitrogen ~ CHRONOLOGY)
summary(DTCNA)
View(DTCNA)
hist(Bronzeanimals$oxygen, xlab="δ18O‰", main="Oxygen data for Animals in Bronze Age", col="chartreuse4")
shapiro.test(Bronzeanimals$oxygen)
hist(Ironanimals$oxygen, xlab="δ18O‰", main="Oxygen data for Animals in Iron Age", col="chocolate2")
shapiro.test(Ironanimals$oxygen)
hist(Medievalanimals$oxygen, xlab="δ18O‰", main="Oxygen data for Animals in the Medieval Period", col="chocolate4")
shapiro.test(Medievalanimals$oxygen)
kruskal.test(animals$oxygen~animals$CHRONOLOGY, data=animals)
DTCOA=dunn_test(animals, oxygen ~ CHRONOLOGY)
summary(DTCOA)
View(DTCOA)
Bronzehuman=subset(human, human$CHRONOLOGY=="BRONZE AGE")

shapiro.test(Bronzehuman$carbon)
Ironhuman=subset(human, human$CHRONOLOGY=="IRON AGE")
hist(Ironhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in the Iron Age", col="bisque2")
shapiro.test(Ironhuman$carbon)
LANThuman=subset(human, human$CHRONOLOGY=="LATE ANTIQUITY")
hist(LANThuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Late Antiquity", col="blanchedalmond")
shapiro.test(LANThuman$carbon)
Medievalhuman=subset(human, human$CHRONOLOGY=="MEDIEVAL")
hist(Medievalhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in the Medieval Period", col="blue4")
shapiro.test(Medievalhuman$carbon)
kruskal.test(human$carbon~human$CHRONOLOGY, data=human)
DTCCH=dunn_test(human, carbon ~ CHRONOLOGY)
summary(DTCCH)
View(DTCCH)
hist(Bronzehuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in the Bronze Age", col="brown2")
shapiro.test(Bronzehuman$nitrogen)
hist(Ironhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in the Iron Age", col="brown4")
shapiro.test(Ironhuman$nitrogen)
hist(LANThuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Late Antiquity", col="cadetblue")
shapiro.test(LANThuman$nitrogen)
hist(Medievalhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in the Medieval period", col="cadetblue2")
shapiro.test(Medievalhuman$nitrogen)
oneway.test(human$nitrogen ~ human$CHRONOLOGY, data=human)
result=aov(human$nitrogen ~ human$CHRONOLOGY, data=human)
TukeyHSD(result)
CHN=TukeyHSD(result)
par(mar=c(5,16,4,1))
plot(CHN, las=1)
hist(Bronzehuman$oxygen, xlab="δ18O‰", main="Oxygen data for Humans in the Bronze Age", col="coral2")
shapiro.test(Bronzehuman$oxygen)
#NEW DAY
aggregate(animals$carbon ~ animals$ENVIRONMENT + animals$CHRONOLOGY, FUN=mean)
MP=aggregate(animals$carbon ~ animals$ENVIRONMENT + animals$CHRONOLOGY, FUN=mean)
View(MP)
plot(MP$`animals$carbon`)
ST=aggregate(animals$carbon ~ animals$SOCIOECONOMIC + animals$CHRONOLOGY, FUN=mean)
VIEW(ST)
plot(ST$`animals$carbon`)
NAE=aggregate(animals$nitrogen ~ animals$ENVIRONMENT + animals$CHRONOLOGY, FUN=mean)
View(NAE)
NAS=aggregate(animals$nitrogen ~ animals$SOCIOECONOMIC + animals$CHRONOLOGY, FUN=mean)
View(NAS)
OAE=aggregate(animals$oxygen ~ animals$ENVIRONMENT + animals$CHRONOLOGY, FUN=mean)
View(OAE)
OAS=aggregate(animals$oxygen ~ animals$SOCIOECONOMIC + animals$CHRONOLOGY, FUN=mean)
View(OAS)
CHE=aggregate(human$carbon ~ human$ENVIRONMENT + human$CHRONOLOGY, FUN=mean)
View(CHE)
CHS=aggregate(human$carbon ~ human$SOCIOECONOMIC + human$CHRONOLOGY, FUN=mean)
View(CHS)
NHS=aggregate(human$nitrogen ~ human$ENVIRONMENT + human$CHRONOLOGY, FUN=mean)
View(NHS)
NHSE=aggregate(human$nitrogen ~ human$SOCIOECONOMIC + human$CHRONOLOGY, FUN=mean)
View(NHSE)
OHE=aggregate(human$oxygen ~ human$ENVIRONMENT + human$CHRONOLOGY, FUN=mean)
View(OHE)
OHS=aggregate(human$oxygen ~ human$SOCIOECONOMIC + human$CHRONOLOGY, FUN=mean)
View(OHS)
caprine=subset(animals, animals$species=="caprine"| animals$species=="ovicaprid"|animals$species=="goat"|animals$species=="sheep"|animals$species=="wild sheep"|animals$species=="ibex")
equus=subset(animals, animals$species=="donkey"|animals$species=="hemione"|animals$species=="horse")
cattle=subset(animals,animals$species=="bos"|animals$species=="cattle")
par(mfrow=c(1,1))
boxplot(caprine$carbon, equus$carbon, cattle$carbon, outline=FALSE)
boxplot(equus$carbon, cattle$carbon, caprine$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Domestic Species ", col=c("orange", "chocolate2", "salmon4"))
axis(1, at=c(1, 2,3), labels=c("Equus", "Cattle", "Caprine"))
boxplot(equus$nitrogen, cattle$nitrogen, caprine$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Domestic Species ", col=c("orange", "chocolate2", "salmon4"))
axis(1, at=c(1, 2,3), labels=c("Equus", "Cattle", "Caprine"))
boxplot(equus$oxygen, cattle$oxygen, caprine$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Domestic Species ", col=c("orange", "chocolate2", "salmon4"))
axis(1, at=c(1, 2,3), labels=c("Equus", "Cattle", "Caprine"))
herbivore=subset(animals, animals$species=="herbivore"|animals$species=="equus"|animals$species=="cattle"|animals$species=="caprine"|animals$species=="camelid"|animals$species=="deer"|animals$species=="red deer"|animals$species=="roe deer"|animals$species=="wild deer"|animals$species=="gazella"|animals$species=="saiga"|animals$species=="tortoise")
omnicarni=subset(animals, animals$species=="pig"|animals$species=="boar"|animals$species=="bear"|animals$species=="dog"|animals$species=="wolf"|animals$species=="cat")
fish=subset(animals, animals$species=="carp"|animals$species=="fish"|animals$species=="pike"|animals$species=="sazan")
boxplot(human$carbon, herbivore$carbon, omnicarni$carbon, fish$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Species Categories ", col=c("lightblue1", "cadetblue3", "royalblue2", "slateblue4"))
axis(1, at=c(1, 2, 3, 4), labels=c("Human", "Herbivore", "Omni/Carnivores", "Marine"))
boxplot(human$nitrogen, herbivore$nitrogen, omnicarni$nitrogen, fish$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Species Categories ", col=c("lightblue1", "cadetblue3", "royalblue2", "slateblue4"))
axis(1, at=c(1, 2, 3, 4), labels=c("Human", "Herbivore", "Omni/Carnivores", "Marine"))
boxplot(human$oxygen, herbivore$oxygen, omnicarni$oxygen, fish$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Species Categories ", col=c("lightblue1", "cadetblue3", "royalblue2", "slateblue4"))
axis(1, at=c(1, 2, 3, 4), labels=c("Human", "Herbivore", "Omni/Carnivores", "Marine"))
Acaprine=subset(caprine, caprine$ENVIRONMENT=="A - SEMI-ARID STEPPE")
Bcaprine=subset(caprine, caprine$ENVIRONMENT=="B - FOREST STEPPE")
Ccaprine=subset(caprine, caprine$ENVIRONMENT=="C - WEST STEPPE")
Dcaprine=subset(caprine, caprine$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
Ecaprine=subset(caprine, caprine$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
Fcaprine=subset(caprine, caprine$ENVIRONMENT=="F - DESERT OASES")
Gcaprine=subset(caprine, caprine$ENVIRONMENT=="G - ARID DESERT")
Aequus=subset(equus, equus$ENVIRONMENT=="A - SEMI-ARID STEPPE")
Bequus=subset(equus, equus$ENVIRONMENT=="B - FOREST STEPPE")
Cequus=subset(equus, equus$ENVIRONMENT=="C - WEST STEPPE")
Dequus=subset(equus, equus$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
Eequus=subset(equus, equus$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
Fequus=subset(equus, equus$ENVIRONMENT=="F - DESERT OASES")
Gequus=subset(equus, equus$ENVIRONMENT=="G - ARID DESERT")
Acattle=subset(cattle, cattle$ENVIRONMENT=="A - SEMI-ARID STEPPE")
Bcattle=subset(cattle, cattle$ENVIRONMENT=="B - FOREST STEPPE")
Ccattle=subset(cattle, cattle$ENVIRONMENT=="C - WEST STEPPE")
Dcattle=subset(cattle, cattle$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
Ecattle=subset(cattle, cattle$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
Fcattle=subset(cattle, cattle$ENVIRONMENT=="F - DESERT OASES")
Gcattle=subset(cattle, cattle$ENVIRONMENT=="G - ARID DESERT")
boxplot(Aequus$carbon, Acattle$carbon, Acaprine$carbon, Bequus$carbon, Bcattle$carbon, Bcaprine$carbon, Cequus$carbon, Ccattle$carbon, Ccaprine$carbon, Dequus$carbon, Dcattle$carbon, Dcaprine$carbon, Eequus$carbon, Ecattle$carbon, Ecaprine$carbon, Fequus$carbon, Fcattle$carbon, Fcaprine$carbon, Gequus$carbon, Gcattle$carbon, Gcaprine$carbon, range=0.5, outline=FALSE, horizontal=TRUE, xlab="δ13C‰", col=c("orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4"))
par(mar=c(5, 1, 1, 1))
par(mfrow=c(1,2))
boxplot(Aequus$carbon, Acattle$carbon, Acaprine$carbon, Bequus$carbon, Bcattle$carbon, Bcaprine$carbon, Cequus$carbon, Ccattle$carbon, Ccaprine$carbon, Dequus$carbon, Dcattle$carbon, Dcaprine$carbon, Eequus$carbon, Ecattle$carbon, Ecaprine$carbon, Fequus$carbon, Fcattle$carbon, Fcaprine$carbon, Gequus$carbon, Gcattle$carbon, Gcaprine$carbon, range=0.7, outline=FALSE, horizontal=TRUE, xlab="δ13C‰", col=c("orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4"), yaxt="n")
axis(4, at=c(2, 5, 8, 11, 14, 17, 20), labels=c("G", "F", "E", "D", "C", "B", "A"), las=2)
boxplot(Aequus$nitrogen, Acattle$nitrogen, Acaprine$nitrogen, Bequus$nitrogen, Bcattle$nitrogen, Bcaprine$nitrogen, Cequus$nitrogen, Ccattle$nitrogen, Ccaprine$nitrogen, Dequus$nitrogen, Dcattle$nitrogen, Dcaprine$nitrogen, Eequus$nitrogen, Ecattle$nitrogen, Ecaprine$nitrogen, Fequus$nitrogen, Fcattle$nitrogen, Fcaprine$nitrogen, Gequus$nitrogen, Gcattle$nitrogen, Gcaprine$nitrogen, range=0.7, outline=FALSE, horizontal=TRUE, xlab="δ15N‰", col=c("orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4"), yaxt="n")
boxplot(Aequus$carbon, Acattle$carbon, Acaprine$carbon, Bequus$carbon, Bcattle$carbon, Bcaprine$carbon, Cequus$carbon, Ccattle$carbon, Ccaprine$carbon, Dequus$carbon, Dcattle$carbon, Dcaprine$carbon, Eequus$carbon, Ecattle$carbon, Ecaprine$carbon, Fequus$carbon, Fcattle$carbon, Fcaprine$carbon, Gequus$carbon, Gcattle$carbon, Gcaprine$carbon, range=0.7, outline=FALSE, horizontal=TRUE, xlab="δ13C‰", col=c("orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4"), yaxt="n", frame.plot="n")
legend(-5,22, legend = "A- Semi-Arid Steppe", bty="n")
legend(-5,18, legend = "B- Forest Steppe", bty="n")
legend(-5,15, legend = "C- West Steppe", bty="n")
legend(-5,12, legend = "D- Mountain/", bty="n")
legend(-5,11, legend = "Forest Steppe", bty="n")
legend(-5,9, legend = "E- Arid/Mountain Steppe", bty="n")
legend(-5,6, legend = "F- Desert Oases", bty="n")
legend(-5,3, legend = "G- Arid Desert", bty="n")
boxplot(Aequus$nitrogen, Acattle$nitrogen, Acaprine$nitrogen, Bequus$nitrogen, Bcattle$nitrogen, Bcaprine$nitrogen, Cequus$nitrogen, Ccattle$nitrogen, Ccaprine$nitrogen, Dequus$nitrogen, Dcattle$nitrogen, Dcaprine$nitrogen, Eequus$nitrogen, Ecattle$nitrogen, Ecaprine$nitrogen, Fequus$nitrogen, Fcattle$nitrogen, Fcaprine$nitrogen, Gequus$nitrogen, Gcattle$nitrogen, Gcaprine$nitrogen, range=0.7, outline=FALSE, horizontal=TRUE, xlab="δ15N‰", col=c("orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4", "orange", "chocolate2", "salmon4"), yaxt="n", frame.plot="n")
legend(0,22, legend = "A- Semi-Arid Steppe", bty="n")
legend(0,18, legend = "B- Forest Steppe", bty="n")
legend(0,15, legend = "C- West Steppe", bty="n")
legend(0,12, legend = "D- Mountain/", bty="n")
legend(0,11, legend = "D- Mountappe", bty="n")
legend(0,9, legend = "E- Arid/Mountain Steppe", bty="n")
legend(0,6, legend = "F- Desert Oases", bty="n")
legend(0,3, legend = "G- Arid Desert", bty="n")
par(mar=c(5, 5, 4, 2))
par(mfrow=c(1,1))
boxplot(Bronzehuman$carbon, Ironhuman$carbon, LANThuman$carbon, Medhuman$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Humans in Different Periods ", col=c("lavenderblush2","pink2", "hotpink3", "magenta4" ))
axis(1, at=c(1, 2, 3, 4), labels=c("Bronze Age", "Iron Age", "Late Antiquity", "Medieval"))
boxplot(Bronzehuman$nitrogen, Ironhuman$nitrogen, LANThuman$nitrogen, Medhuman$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Humans in Different Periods ", col=c("lavenderblush2","pink2", "hotpink3", "magenta4" ))
axis(1, at=c(1, 2, 3, 4), labels=c("Bronze Age", "Iron Age", "Late Antiquity", "Medieval"))
boxplot(Bronzehuman$oxygen, Ironhuman$oxygen, LANThuman$oxygen, Medhuman$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Humans in Different Periods ", col=c("lavenderblush2","pink2", "hotpink3", "magenta4" ))
axis(1, at=c(1, 2, 3, 4), labels=c("Bronze Age", "Iron Age", "Late Antiquity", "Medieval"))
boxplot(Bronzeanimals$carbon, Ironanimals$carbon, LANTanimals$carbon, MEDanimals$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Animals in Different Periods ", col=c("chartreuse1", "seagreen3","springgreen4", "olivedrab4"))
axis(1, at=c(1, 2, 3, 4), labels=c("Bronze Age", "Iron Age", "Late Antiquity", "Medieval"))
boxplot(Bronzeanimals$nitrogen, Ironanimals$nitrogen, LANTanimals$nitrogen, MEDanimals$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Animals in Different Periods ", col=c("chartreuse1", "seagreen3","springgreen4", "olivedrab4"))
axis(1, at=c(1, 2, 3, 4), labels=c("Bronze Age", "Iron Age", "Late Antiquity", "Medieval"))
boxplot(Bronzeanimals$oxygen, Ironanimals$oxygen, LANTanimals$oxygen, MEDanimals$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Animals in Different Periods ", col=c("chartreuse1", "seagreen3","springgreen4", "olivedrab4"))
axis(1, at=c(1, 2, 3, 4), labels=c("Bronze Age", "Iron Age", "Late Antiquity", "Medieval"))
Aanimals=subset(animals, animals$ENVIRONMENT=="A - SEMI-ARID STEPPE")
Banimals=subset(animals, animals$ENVIRONMENT=="B - FOREST STEPPE")
Canimals=subset(animals, animals$ENVIRONMENT=="C - WEST STEPPE")
Danimals=subset(animals, animals$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
Eanimals=subset(animals, animals$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
Fanimals=subset(animals, animals$ENVIRONMENT=="F - DESERT OASES")
Ganimals=subset(animals, animals$ENVIRONMENT=="G - ARID DESERT")
Ahuman=subset(human, human$ENVIRONMENT=="A - SEMI-ARID STEPPE")
Bhuman=subset(human, human$ENVIRONMENT=="B - FOREST STEPPE")
Chuman=subset(human, human$ENVIRONMENT=="C - WEST STEPPE")
Dhuman=subset(human, human$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
Ehuman=subset(human, human$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
Fhuman=subset(human, human$ENVIRONMENT=="F - DESERT OASES")
Ghuman=subset(human, human$ENVIRONMENT=="G - ARID DESERT")
boxplot(Aanimals$carbon, Banimals$carbon, Canimals$carbon, Danimals$carbon, Eanimals$carbon, Fanimals$carbon, Ganimals$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Animals in Different Environments ", col=c("antiquewhite", "moccasin", "peachpuff3", "cornsilk3","slategrey", "dimgray","darkslategray"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A-Semi-Arid Steppe", "B-Forest Steppe", "C-West Steppe", "D-Mountain/Forest Steppe", "E-Arid/Mountain Steppe", "F-Desert Oases", "G-Arid Desert"), cex.axis=0.6)
boxplot(Aanimals$carbon, Banimals$carbon, Canimals$carbon, Danimals$carbon, Eanimals$carbon, Fanimals$carbon, Ganimals$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Animals in Different Environments ", col=c("antiquewhite", "moccasin", "peachpuff3", "cornsilk3","slategrey", "dimgray","darkslategray"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A", "B", "C", "D", "E", "F", "G"), cex.axis=1.7)
boxplot(Aanimals$nitrogen, Banimals$nitrogen, Canimals$nitrogen, Danimals$nitrogen, Eanimals$nitrogen, Fanimals$nitrogen, Ganimals$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Animals in Different Environments ", col=c("antiquewhite", "moccasin", "peachpuff3", "cornsilk3","slategrey", "dimgray","darkslategray"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A-Semi-Arid Steppe", "B-Forest Steppe", "C-West Steppe", "D-Mountain/Forest Steppe", "E-Arid/Mountain Steppe", "F-Desert Oases", "G-Arid Desert"), cex.axis=0.6)
boxplot(Aanimals$oxygen, Banimals$oxygen, Canimals$oxygen, Danimals$oxygen, Eanimals$oxygen, Fanimals$oxygen, Ganimals$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Animals in Different Environments ",  col=c("antiquewhite", "moccasin", "peachpuff3", "cornsilk3","slategrey", "dimgray","darkslategray"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A-Semi-Arid Steppe", "B-Forest Steppe", "C-West Steppe", "D-Mountain/Forest Steppe", "E-Arid/Mountain Steppe", "F-Desert Oases", "G-Arid Desert"), cex.axis=0.6)
boxplot(Ahuman$carbon, Bhuman$carbon, Chuman$carbon, Dhuman$carbon, Ehuman$carbon, Fhuman$carbon, Ghuman$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Humans in Different Environments ", col=c("azure", "pink", "springgreen2","yellow", "red", "purple","brown"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A-Semi-Arid Steppe", "B-Forest Steppe", "C-West Steppe", "D-Mountain/Forest Steppe", "E-Arid/Mountain Steppe", "F-Desert Oases", "G-Arid Desert"), cex.axis=0.6)
boxplot(Ahuman$nitrogen, Bhuman$nitrogen, Chuman$nitrogen, Dhuman$nitrogen, Ehuman$nitrogen, Fhuman$nitrogen, Ghuman$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Humans in Different Environments ", col=c("azure", "pink", "springgreen2","yellow", "red", "purple","brown"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A-Semi-Arid Steppe", "B-Forest Steppe", "C-West Steppe", "D-Mountain/Forest Steppe", "E-Arid/Mountain Steppe", "F-Desert Oases", "G-Arid Desert"), cex.axis=0.6)
boxplot(Ahuman$oxygen, Bhuman$oxygen, Chuman$oxygen, Dhuman$oxygen, Ehuman$oxygen, Fhuman$oxygen, Ghuman$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Humans in Different Environments ", col=c("azure", "pink", "springgreen2","yellow", "red", "purple","brown"))
axis(1, at=c(1, 2, 3, 4, 5, 6, 7), labels=c("A-Semi-Arid Steppe", "B-Forest Steppe", "C-West Steppe", "D-Mountain/Forest Steppe", "E-Arid/Mountain Steppe", "F-Desert Oases", "G-Arid Desert"), cex.axis=0.6)
boxplot(urbanhuman$carbon, nomadhuman$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Humans in Urban or Nomadic Societies", col=c("lightgray", "darkslategray"))
axis(1, at=c(1, 2), labels=c("Urban", "Nomadic"), cex.axis=1.5)
boxplot(urbanhuman$nitrogen, nomadhuman$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Humans in Urban or Nomadic Societies", col=c("lightgray", "darkslategray"))
axis(1, at=c(1, 2), labels=c("Urban", "Nomadic"), cex.axis=1.5)
boxplot(urbananimal$carbon, nomadanimal$carbon, outline=FALSE, ylab="δ13C‰", main="Carbon Isotopic Differences in Animals in Urban or Nomadic Societies", col=c("lightpink2", "magenta4"))
axis(1, at=c(1, 2), labels=c("Urban", "Nomadic"), cex.axis=1.5)
boxplot(urbananimal$nitrogen, nomadanimal$nitrogen, outline=FALSE, ylab="δ15N‰", main="Nitrogen Isotopic Differences in Animals in Urban or Nomadic Societies", col=c("lightpink2", "magenta4"))
axis(1, at=c(1, 2), labels=c("Urban", "Nomadic"), cex.axis=1.5)
boxplot(urbananimal$oxygen, nomadanimal$oxygen, outline=FALSE, ylab="δ18O‰", main="Oxygen Isotopic Differences in Animals in Urban or Nomadic Societies", col=c("lightpink2", "magenta4"))
axis(1, at=c(1, 2), labels=c("Urban", "Nomadic"), cex.axis=1.5)
NBanimals=subset(nomadanimal, nomadanimal$CHRONOLOGY=="BRONZE AGE")
par(mfrow=c(1,1))
par(mar=c(5, 5, 4, 2))
hist(NBanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Nomadic Bronze Age", col="red") 
shapiro.test(NBanimals$carbon)
NIanimals=subset(nomadanimal, nomadanimal$CHRONOLOGY=="IRON AGE")
hist(NIanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Nomadic Iron Age", col="lightblue") 
shapiro.test(NIanimals$carbon)
NLanimals=subset(nomadanimal, nomadanimal$CHRONOLOGY=="LATE ANTIQUITY")
hist(NLanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Nomadic Late Antiquity", col="lavender") 
shapiro.test(NLanimals$carbon)
NManimals=subset(nomadanimal, nomadanimal$CHRONOLOGY=="MEDIEVAL")
hist(NManimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Nomadic Medieval Period", col="lightpink") 
shapiro.test(NManimals$carbon)
kruskal.test(nomadanimal$carbon ~ nomadanimal$CHRONOLOGY, data=nomadanimal)

