CNAC=dunn_test(nomadanimal, carbon ~ CHRONOLOGY) 
summary(CNAC)
View(CNAC)
UBanimal=subset(urbananimal, urbananimal$CHRONOLOGY=="BRONZE AGE")
hist(UBanimal$carbon, xlab="δ13C‰", main="Carbon data for animals in Urban Bronze Age", col="yellow2")
shapiro.test(UBanimal$carbon)
UIanimal=subset(urbananimal, urbananimal$CHRONOLOGY=="IRON AGE")
ULanimal=subset(urbananimal, urbananimal$CHRONOLOGY=="LATE ANTIQUITY")
UManimal=subset(urbananimal, urbananimal$CHRONOLOGY=="MEDIEVAL")
hist(UManimal$carbon, xlab="δ13C‰", main="Carbon data for animals in Urban Medieval", col="tan2")
shapiro.test(UManimal$carbon)
wilcox.test(x=UBanimal$carbon, y=UManimal$carbon) 
NBhuman=subset(nomadhuman, nomadhuman$CHRONOLOGY=="BRONZE AGE")
hist(NBhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Nomadic Bronze Age", col="plum")
shapiro.test(NBhuman$carbon)
NIhuman=subset(nomadhuman, nomadhuman$CHRONOLOGY=="IRON AGE")
hist(NIhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Nomadic Iron Age", col="slategray")
shapiro.test(NIhuman$carbon)
NLhuman=subset(nomadhuman, nomadhuman$CHRONOLOGY=="LATE ANTIQUITY")
hist(NLhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Nomadic Late Antiquity", col="cadetblue2")
shapiro.test(NLhuman$carbon)
NMhuman=subset(nomadhuman, nomadhuman$CHRONOLOGY=="MEDIEVAL")
hist(NMhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Nomadic Medieval period", col="springgreen4")
shapiro.test(NMhuman$carbon)
kruskal.test(nomadhuman$carbon ~ nomadhuman$CHRONOLOGY, data=nomadhuman)
CNHC=dunn_test(nomadhuman, carbon~CHRONOLOGY)
summary(CNHC)
View(CNHC)
UBhuman=subset(urbanhuman, urbanhuman$CHRONOLOGY=="BRONZE AGE")
hist(UBhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Urban Bronze Age", col="forestgreen")
UIhuman=subset(urbanhuman, urbanhuman$CHRONOLOGY=="IRON AGE")
hist(UIhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Urban Iron Age", col="salmon2")
ULhuman=subset(urbanhuman, urbanhuman$CHRONOLOGY=="LATE ANTIQUITY")
UMhuman=subset(urbanhuman, urbanhuman$CHRONOLOGY=="MEDIEVAL")
hist(UMhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Urban MEDIEVAL", col="sienna2")
shapiro.test(UMhuman$carbon)
kruskal.test(urbanhuman$carbon ~ urbanhuman$CHRONOLOGY, data=urbanhuman)
CUHC=dunn_test(urbanhuman, carbon~CHRONOLOGY)
summary(CUHC)
View(CUHC)
hist(NBanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Nomadic Bronze Age", col="tomato4")
shapiro.test(NBanimals$nitrogen)
hist(NIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Nomadic Iron Age", col="peru")
shapiro.test(NIanimals$nitrogen)
hist(NLanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Nomadic Late Antiquity", col="aquamarine4")
shapiro.test(NLanimals$nitrogen)
kruskal.test(nomadanimal$nitrogen~nomadanimal$CHRONOLOGY, data=nomadanimal)
NANC=dunn_test(nomadanimal, nitrogen~CHRONOLOGY)
summary(NANC)
View(NANC)
hist(UBanimal$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Urban Bronze Age", col="steelblue3")
shapiro.test(UBanimal$nitrogen)
hist(UManimal$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Urban Medieval period", col="sienna3")
shapiro.test(UManimal$nitrogen)
t.test(x=UBanimal$nitrogen, y=UManimal$nitrogen)
hist(NBhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Nomadic Bronze Age", col="tomato2")
shapiro.test(NBhuman$nitrogen)
hist(NIhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Nomadic Iron Age", col="lightblue2")
shapiro.test(NIhuman$nitrogen)
hist(NLhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Nomadic Late Antiquity", col="lightgreen")
shapiro.test(NLhuman$nitrogen)
hist(NMhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Nomadic Medieval", col="sandybrown")
shapiro.test(NMhuman$nitrogen)
kruskal.test(nomadhuman$nitrogen~nomadhuman$CHRONOLOGY, data=nomadhuman)
NHNC=dunn_test(nomadhuman, nitrogen~CHRONOLOGY)
summary(NHNC)
View(NHNC)
hist(UBhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Urban Bronze Age", col="turquoise")
hist(UIhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Urban Iron Age", col="turquoise3")
hist(UMhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Urban Medieval Period", col="chocolate2")
shapiro.test(UMhuman$nitrogen)
kruskal.test(urbanhuman$nitrogen~urbanhuman$CHRONOLOGY, data=urbanhuman)
NHUC=dunn_test(urbanhuman, nitrogen~CHRONOLOGY)
summary(NHUC)
View(NHUC)
hist(NBanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Nomadic bronze Age", col="plum4")
shapiro.test(NBanimals$oxygen)
hist(NIanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Nomadic Iron Age", col="azure4")
shapiro.test(NIanimals$oxygen)
hist(NManimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Nomadic Medieval", col="lightblue3")
shapiro.test(NManimals$oxygen)
kruskal.test(nomadanimal$oxygen~nomadanimal$CHRONOLOGY, data=nomadanimal)
hist(UBanimal$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Urban Bronze Age", col="orange")
shapiro.test(UBanimal$oxygen)
ABanimals=subset(Aanimals, Aanimals$CHRONOLOGY=="BRONZE AGE")
hist(ABanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Semi-Arid Steppes in the Bronze Age", col="greenyellow")
shapiro.test(ABanimals$carbon)
AIanimals=subset(Aanimals, Aanimals$CHRONOLOGY=="IRON AGE")
hist(AIanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Semi-Arid Steppes in the Iron Age", col="khaki2")
shapiro.test(AIanimals$carbon)
ALanimals=subset(Aanimals, Aanimals$CHRONOLOGY=="LATE ANTIQUITY")
hist(ALanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Semi-Arid Steppes in the Late Antiquity", col="darkorange")
AManimals=subset(Aanimals, Aanimals$CHRONOLOGY=="MEDIEVAL")
hist(AManimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Semi-Arid Steppes in the Late Medieval", col="chocolate")
kruskal.test(Aanimals$carbon~Aanimals$CHRONOLOGY, data=Aanimals)
CAAC=dunn_test(Aanimals, carbon~CHRONOLOGY)
summary(CAAC)
View(CAAC)
BBanimals=subset(Banimals, Banimals$CHRONOLOGY=="BRONZE AGE")
hist(BBanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Forest Steppes in Bronze Age", col="chocolate4")
shapiro.test(BBanimals$carbon)
BIanimals=subset(Banimals, Banimals$CHRONOLOGY=="IRON AGE")
hist(BIanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Forest Steppes in Iron Age", col="navy")
shapiro.test(BIanimals$carbon)

BLanimals=subset(Banimals, Banimals$CHRONOLOGY=="LATE ANTIQUITY")
BManimals=subset(Banimals, Banimals$CHRONOLOGY=="MEDIEVAL")
kruskal.test(Banimals$carbon~Banimals$CHRONOLOGY, data=Banimals)
CABC=dunn_test(Banimals, carbon~CHRONOLOGY)
summary(CABC)
View(CABC)
CBanimals=subset(Canimals, Canimals$CHRONOLOGY=="BRONZE AGE")
hist(CBanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in West Steppes in Bronze Age", col="hotpink2")
CIanimals=subset(Canimals, Canimals$CHRONOLOGY=="IRON AGE")
hist(CIanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in West Steppes in Iron Age", col="yellowgreen")
shapiro.test(CIanimals$carbon)
CLanimals=subset(Canimals, Canimals$CHRONOLOGY=="LATE ANTIQUITY")
CManimals=subset(Canimals, Canimals$CHRONOLOGY=="MEDIEVAL")
t.test(x=CBanimals$carbon, y=CIanimals$carbon) 
wilcox.test(x=CBanimals$carbon, y=CIanimals$carbon) 
DBanimals=subset(Danimals, Danimals$CHRONOLOGY=="BRONZE AGE")
hist(DBanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Mountain/Forest Steppe in Bronze Age", col="lawngreen")
shapiro.test(DBanimals$carbon)
DIanimals=subset(Danimals, Danimals$CHRONOLOGY=="IRON AGE")
hist(DIanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Mountain/Forest Steppe in Iron Age", col="paleturquoise")
shapiro.test(DIanimals$carbon)
DLanimals=subset(Danimals, Danimals$CHRONOLOGY=="LATE ANTIQUITY")
DManimals=subset(Danimals, Danimals$CHRONOLOGY=="MEDIEVAL")
wilcox.test(x=DBanimals$carbon, y=DIanimals$carbon) 
EBanimals=subset(Eanimals, Eanimals$CHRONOLOGY=="BRONZE AGE")
hist(EBanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Arid/Mountain Steppe in Bronze Age", col="plum2")
shapiro.test(EBanimals$carbon)
EIanimals=subset(Eanimals, Eanimals$CHRONOLOGY=="IRON AGE")
hist(EIanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Arid/Mountain Steppe in Iron Age", col="magenta4")
shapiro.test(EIanimals$carbon)
ELanimals=subset(Eanimals, Eanimals$CHRONOLOGY=="LATE ANTIQUITY")
hist(ELanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Arid/Mountain Steppe in Late Antiquity", col="seagreen4")
shapiro.test(ELanimals$carbon)
EManimals=subset(Eanimals, Eanimals$CHRONOLOGY=="MEDIEVAL")
hist(EManimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Arid/Mountain Steppe in Medieval", col="tomato4")
shapiro.test(EManimals$carbon)
kruskal.test(Eanimals$carbon~Eanimals$CHRONOLOGY, data=Eanimals)
CAEC=dunn_test(Eanimals, carbon~CHRONOLOGY)
summary(CAEC)
View(CAEC)
FBanimals=subset(Fanimals, Fanimals$CHRONOLOGY=="BRONZE AGE")
FIanimals=subset(Fanimals, Fanimals$CHRONOLOGY=="IRON AGE")
hist(FIanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Desert Oases in Iron Age", col="slateblue")
shapiro.test(FIanimals$carbon)
FLanimals=subset(Fanimals, Fanimals$CHRONOLOGY=="LATE ANTIQUITY")
hist(FLanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Desert Oases in Late Antiquity", col="slategray3")
shapiro.test(FLanimals$carbon)
FManimals=subset(Fanimals, Fanimals$CHRONOLOGY=="MEDIEVAL")
hist(FManimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Desert Oases in Medieval", col="grey")
kruskal.test(Fanimals$carbon~Fanimals$CHRONOLOGY, data=Fanimals)

CAFC=dunn_test(Fanimals, carbon~CHRONOLOGY)
summary(CAFC)
View(CAFC)
GBanimals=subset(Ganimals, Ganimals$CHRONOLOGY=="BRONZE AGE")
hist(GBanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Arid Desert in Bronze Age", col="peachpuff2")
shapiro.test(GBanimals$carbon)
GIanimals=subset(Ganimals, Ganimals$CHRONOLOGY=="IRON AGE")
GLanimals=subset(Ganimals, Ganimals$CHRONOLOGY=="LATE ANTIQUITY")
GManimals=subset(Ganimals, Ganimals$CHRONOLOGY=="MEDIEVAL")
hist(GManimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Arid Desert in Medieval", col="darkslategray")
shapiro.test(GManimals$carbon)
wilcox.test(x=GBanimals$carbon, y=GManimals$carbon) 
ABhumans=subset(Ahuman, Ahuman$CHRONOLOGY=="BRONZE AGE")
hist(ABhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Semi-Arid Steppe in Bronze Age", col="wheat3")
shapiro.test(ABhumans$carbon)
AIhumans=subset(Ahuman, Ahuman$CHRONOLOGY=="IRON AGE")
hist(AIhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Semi-Arid Steppe in Iron Age", col="violetred4")
shapiro.test(AIhumans$carbon)
ALhumans=subset(Ahuman, Ahuman$CHRONOLOGY=="LATE ANTIQUITY")
hist(ALhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Semi-Arid Steppe in Late Antiquity", col="violetred")
shapiro.test(ALhumans$carbon)
AMhumans=subset(Ahuman, Ahuman$CHRONOLOGY=="MEDIEVAL")
hist(AMhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Semi-Arid Steppe in Medieval", col="turquoise4")
shapiro.test(AMhumans$carbon)
kruskal.test(Ahuman$carbon~Ahuman$CHRONOLOGY, data=Ahuman)
CHAC=dunn_test(Ahuman, carbon~CHRONOLOGY)
summary(CHAC)
View(CHAC)
BBhumans=subset(Bhuman, Bhuman$CHRONOLOGY=="BRONZE AGE")
hist(BBhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Forest Steppe in Bronze Age", col="turquoise")
shapiro.test(BBhumans$carbon)
BIhumans=subset(Bhuman, Bhuman$CHRONOLOGY=="IRON AGE")
hist(BIhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Forest Steppe inIRON Age", col="tomato3")
shapiro.test(BIhumans$carbon)
BLhumans=subset(Bhuman, Bhuman$CHRONOLOGY=="LATE ANTIQUITY")
hist(BLhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Forest Steppe in Late Antiquity", col="thistle3")
shapiro.test(BLhumans$carbon)
BMhumans=subset(Bhuman, Bhuman$CHRONOLOGY=="MEDIEVAL")
hist(BMhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Forest Steppe in Medieval", col="thistle1")
shapiro.test(BMhumans$carbon)
kruskal.test(Bhuman$carbon~Bhuman$CHRONOLOGY, data=Bhuman)
CHBC=dunn_test(Bhuman, carbon~CHRONOLOGY)
summary(CHBC)
View(CHBC)
CBhumans=subset(Chuman, Chuman$CHRONOLOGY=="BRONZE AGE")
hist(CBhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in West Steppe in Bronze Age", col="tan4")
shapiro.test(CBhumans$carbon)
CIhumans=subset(Chuman, Chuman$CHRONOLOGY=="IRON AGE")
hist(CIhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in West Steppe in Iron Age", col="tan1")
shapiro.test(CIhumans$carbon)
CLhumans=subset(Chuman, Chuman$CHRONOLOGY=="LATE ANTIQUITY")
CMhumans=subset(Chuman, Chuman$CHRONOLOGY=="MEDIEVAL")
wilcox.test(x=CBhumans$carbon, y=CIhumans$carbon) 
DBhumans=subset(Dhuman, Dhuman$CHRONOLOGY=="BRONZE AGE")
hist(DBhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Mountain/Forest Steppe in Bronze Age", col="steelblue2")
shapiro.test(DBhumans$carbon)
DIhumans=subset(Dhuman, Dhuman$CHRONOLOGY=="IRON AGE")
hist(DIhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Mountain/Forest Steppe in Iron Age", col="springgreen4")
shapiro.test(DIhumans$carbon)
DLhumans=subset(Dhuman, Dhuman$CHRONOLOGY=="LATE ANTIQUITY")
DMhumans=subset(Dhuman, Dhuman$CHRONOLOGY=="MEDIEVAL")
t.test(x=DBhumans$carbon, y=DIhumans$carbon) 
EBhumans=subset(Ehuman, Ehuman$CHRONOLOGY=="BRONZE AGE")
hist(EBhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid/Mountain Steppe in Bronze Age", col="springgreen2")
shapiro.test(EBhumans$carbon)
EIhumans=subset(Ehuman, Ehuman$CHRONOLOGY=="IRON AGE")
hist(EIhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid/Mountain Steppe in Iron Age", col="snow4")
shapiro.test(EIhumans$carbon)
ELhumans=subset(Ehuman, Ehuman$CHRONOLOGY=="LATE ANTIQUITY")
hist(ELhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid/Mountain Steppe in Late Antiquity", col="slategrey")
shapiro.test(ELhumans$carbon)
EMhumans=subset(Ehuman, Ehuman$CHRONOLOGY=="MEDIEVAL")
hist(EMhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid/Mountain Steppe in Medieval", col="slateblue3")
shapiro.test(EMhumans$carbon)
kruskal.test(Ehuman$carbon~Ehuman$CHRONOLOGY, data=Ehuman)
CHEC=dunn_test(Ehuman, carbon~CHRONOLOGY)
summary(CHEC)
View(CHEC)
FBhumans=subset(Fhuman, Fhuman$CHRONOLOGY=="BRONZE AGE")
FIhumans=subset(Fhuman, Fhuman$CHRONOLOGY=="IRON AGE")
hist(FIhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Desert Oases in Iron Age", col="skyblue4")
shapiro.test(FIhumans$carbon)
FLhumans=subset(Fhuman, Fhuman$CHRONOLOGY=="LATE ANTIQUITY")
hist(FLhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Desert Oases in Late Antiquity", col="skyblue1")
shapiro.test(FLhumans$carbon)
FMhumans=subset(Fhuman, Fhuman$CHRONOLOGY=="MEDIEVAL")
hist(FMhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Desert Oases in Medieval", col="sienna4")
shapiro.test(FMhumans$carbon)
kruskal.test(Fhuman$carbon~Fhuman$CHRONOLOGY, data=Fhuman)
CHFC=dunn_test(Fhuman, carbon~CHRONOLOGY)
summary(CHFC)
View(CHFC)
GBhumans=subset(Ghuman, Ghuman$CHRONOLOGY=="BRONZE AGE")
hist(GBhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid Desert in Bronze Age", col="sienna1")
GIhumans=subset(Ghuman, Ghuman$CHRONOLOGY=="IRON AGE")
GLhumans=subset(Ghuman, Ghuman$CHRONOLOGY=="LATE ANTIQUITY")
hist(GLhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid Desert in Late Antiquity", col="seashell4")
GMhumans=subset(Ghuman, Ghuman$CHRONOLOGY=="MEDIEVAL")
hist(GMhumans$carbon, xlab="δ13C‰", main="Carbon data for humans in Arid Desert in Medieval", col="seashell3")
kruskal.test(Ghuman$carbon~Ghuman$CHRONOLOGY, data=Ghuman)
CHGC=dunn_test(Ghuman, carbon~CHRONOLOGY)
summary(CHGC)
View(CHGC)
hist(ABanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Semi-Arid Steppe in Bronze Age", col="seagreen")
shapiro.test(ABanimals$nitrogen)
hist(AIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Semi-Arid Steppe in Iron Age", col="salmon4")
shapiro.test(AIanimals$nitrogen)
hist(ALanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Semi-Arid Steppe in Late Antiquity", col="salmon2")
hist(AManimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Semi-Arid Steppe in Medieval", col="salmon")
kruskal.test(Aanimals$nitrogen~Aanimals$CHRONOLOGY, data=Aanimals)
NAAC=dunn_test(Aanimals, nitrogen~CHRONOLOGY)
summary(NAAC)
View(NAAC)
hist(BBanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Forest Steppe in Bronze Age", col="saddlebrown")
shapiro.test(BBanimals$nitrogen)
hist(BIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Forest Steppe in Iron Age", col="royalblue4")
shapiro.test(BIanimals$nitrogen)
hist(BManimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Forest Steppe in Medieval", col="royalblue2")
kruskal.test(Banimals$nitrogen~Banimals$CHRONOLOGY, data=Banimals)
hist(CBanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in West Steppe in Bronze Age", col="rosybrown 4")
shapiro.test(CBanimals$nitrogen)
hist(CIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in West Steppe in Iron Age", col="rosybrown2")
shapiro.test(CIanimals$nitrogen)
wilcox.test(x=CBanimals$nitrogen, y=CIanimals$nitrogen) 
hist(DBanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Mountain/Forest Steppe in Bronze Age", col="red4")
shapiro.test(DBanimals$nitrogen)
hist(DIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Mountain/Forest Steppe in Iron Age", col="red2")
shapiro.test(DIanimals$nitrogen)
wilcox.test(x=DBanimals$nitrogen, y=DIanimals$nitrogen) 
hist(EBanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid/Mountain Steppe in Bronze Age", col="purple4")
hist(EIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid/Mountain Steppe in Iron Age", col="purple2")
shapiro.test(EBanimals$nitrogen)
shapiro.test(EIanimals$nitrogen)
hist(ELanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid/Mountain Steppe in Late Antiquity", col="powderblue")
shapiro.test(ELanimals$nitrogen)
oneway.test(Eanimals$nitrogen ~ Eanimals$CHRONOLOGY, data=Eanimals)
result=aov(Eanimals$nitrogen ~ Eanimals$CHRONOLOGY, data=Eanimals) 
TukeyHSD(result)
plot(result) 
T=TukeyHSD(result) 
par(mar=c(5,16,4,1)) 
plot(T, las=1) 
par(mar=c(5,5,4,2))
hist(FIanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Desert Oases in Iron Age", col="pink4")
shapiro.test(FIanimals$nitrogen)
hist(FLanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Desert Oases in Late Antiquity", col="pink2")
shapiro.test(FLanimals$nitrogen)
hist(FManimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Desert Oases in Late Medieval", col="peru")
kruskal.test(Fanimals$nitrogen~Fanimals$CHRONOLOGY, data=Fanimals)
NAFC=dunn_test(Fanimals, nitrogen~CHRONOLOGY)
summary(NAFC)
View(NAFC)
hist(GBanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid Desert in Bronze Age", col="peachpuff4")
shapiro.test(GBanimals$nitrogen)
hist(GManimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid Desert in Medieval", col="peachpuff2")
shapiro.test(GManimals$nitrogen)
t.test(x=GBanimals$nitrogen, y=GManimals$nitrogen) 
hist(ABhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Semi-Arid Steppe in Bronze Age", col="papayawhip")
shapiro.test(ABhumans$nitrogen)
hist(AIhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Semi-Arid Steppe in IRON Age", col="palevioletred4")
shapiro.test(AIhumans$nitrogen)
hist(ALhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Semi-Arid Steppe in Late Antiquity", col="palevioletred2")
shapiro.test(ALhumans$nitrogen)
hist(AMhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Semi-Arid Steppe in Medieval", col="paleturquoise4")
shapiro.test(AMhumans$nitrogen)
kruskal.test(Ahuman$nitrogen~Ahuman$CHRONOLOGY, data=Ahuman)
NHAC=dunn_test(Ahuman, nitrogen~CHRONOLOGY)
summary(NHAC)
View(NHAC)
hist(BBhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Forest Steppe in Bronze Age", col="paleturquoise2")
shapiro.test(BBhumans$nitrogen)
hist(BIhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Forest Steppe in Iron Age", col="palegreen4")
shapiro.test(BIhumans$nitrogen)

hist(BLhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Forest Steppe in Late Antiquity", col="palegreen2")
shapiro.test(BLhumans$nitrogen)
hist(BMhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Forest Steppe in Medieval", col="palegoldenrod")
shapiro.test(BMhumans$nitrogen)
kruskal.test(Bhuman$nitrogen~Bhuman$CHRONOLOGY, data=Bhuman)
hist(CBhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in West Steppe in Bronze Age", col="orchid4")
shapiro.test(CBhumans$nitrogen)
hist(CIhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in West Steppe in Iron Age", col="orchid2")
shapiro.test(CIhumans$nitrogen)
wilcox.test(x=CBhumans$nitrogen, y=CIhumans$nitrogen) 
hist(DBhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Mountain/Forest Steppe in Bronze Age", col="orangered4")
shapiro.test(DBhumans$nitrogen)
hist(DIhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Mountain/Forest Steppe in Iron Age", col="orangered2")
shapiro.test(DIhumans$nitrogen)
wilcox.test(x=DBhumans$nitrogen, y=DIhumans$nitrogen) 
hist(EBhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid/Mountain Steppe in Bronze Age", col="orange3")
shapiro.test(EBhumans$nitrogen)
hist(EIhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid/Mountain Steppe in Iron Age", col="orange")
shapiro.test(EIhumans$nitrogen)
hist(ELhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid/Mountain Steppe in Late Antiquity", col="olivedrab4")
shapiro.test(ELhumans$nitrogen)
hist(EMhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid/Mountain Steppe in Medieval", col="olivedrab2")
shapiro.test(EMhumans$nitrogen)
kruskal.test(Ehuman$nitrogen~Ehuman$CHRONOLOGY, data=Ehuman)
NHEC=dunn_test(Ehuman, nitrogen~CHRONOLOGY)
summary(NHEC)
View(NHEC)
hist(FIhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Desert Oases in Iron Age", col="navyblue")
shapiro.test(FIhumans$nitrogen)
hist(FLhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Desert Oases in Late Antiquity", col="navajowhite4")
shapiro.test(FLhumans$nitrogen)
hist(FMhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Desert Oases in Medieval", col="navajowhite2")
shapiro.test(FMhumans$nitrogen)
oneway.test(Fhuman$nitrogen ~ Fhuman$CHRONOLOGY, data=Fhuman) 
result=aov(Fhuman$nitrogen ~ Fhuman$CHRONOLOGY, data=Fhuman)
TukeyHSD(result)
T=TukeyHSD(result) 
par(mar=c(5,16,5,1)) 
plot(T, las=1) 
hist(GBhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid Desert in Bronze Age", col="moccasin")
hist(GLhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid Desert in Late Antiquity", col="mistyrose4")
hist(GMhumans$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Arid Desert in Medieval", col="mistyrose2")
kruskal.test(Ghuman$nitrogen~Ghuman$CHRONOLOGY, data=Ghuman)
hist(ABanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Semi-Arid Steppe in Bronze Age", col="midnightblue")
shapiro.test(ABanimals$oxygen)
hist(DIanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Mountain/Forest Steppe in Iron Age", col="mediumvioletred")
shapiro.test(DIanimals$oxygen)
hist(EBanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid/Mountain Steppe in Bronze Age", col="mediumturquoise")
shapiro.test(EBanimals$oxygen)
hist(EIanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid/Mountain Steppe in Iron Age", col="mediumspringgreen")
shapiro.test(EIanimals$oxygen)
hist(EManimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid/Mountain Steppe in Medieval", col="mediumslateblue")
shapiro.test(EManimals$oxygen)
oneway.test(Eanimals$oxygen ~ Eanimals$CHRONOLOGY, data=Eanimals) 
hist(GBanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid Desert in Bronze Age", col="mediumseagreen")
shapiro.test(GBanimals$oxygen)
hist(BBhumans$oxygen, xlab="δ18O‰", main="Oxygen data for humans in Forest Steppe in Bronze Age", col="mediumpurple4")
shapiro.test(BBhumans$oxygen)
